#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/mrjackiechan/{application}
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10000/eureka
#
